# Generated by Django 5.0.3 on 2024-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
