# Generated by Django 5.0.3 on 2024-03-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvideo1', models.FileField(upload_to='static/images/')),
                ('hvideo2', models.FileField(upload_to='static/images/')),
            ],
        ),
    ]
