# Generated by Django 5.0.3 on 2024-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_hvideomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htopicimg', models.ImageField(upload_to='static/images/')),
                ('htopicimgt', models.TextField(max_length=100)),
            ],
        ),
    ]
