# Generated by Django 5.0.3 on 2024-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_hsvideomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hgc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Hgc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Hgc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Hgc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
