# Generated by Django 5.0.3 on 2024-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_hgc1model_hgc2model_hgc3model_hgc4model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fimg', models.ImageField(upload_to='static/images/')),
                ('cpimg', models.ImageField(upload_to='static/images/')),
                ('cname', models.CharField(max_length=200)),
                ('cfeedback', models.CharField(max_length=200)),
            ],
        ),
    ]
