# Generated by Django 5.0.3 on 2024-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_cfeedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
