# Generated by Django 5.0.3 on 2024-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_lvideomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltopicimg', models.ImageField(upload_to='static/images/')),
                ('ltopicimgt', models.TextField(max_length=100)),
            ],
        ),
    ]
