# Generated by Django 5.0.3 on 2024-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_ltopicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
    ]
