# Generated by Django 5.0.3 on 2024-03-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0011_lgc1model_lgc2model_lgc3model_lgc4model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kgc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Kgc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Kgc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Kgc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='KsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='KsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='KtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktopicimg', models.ImageField(upload_to='static/images/')),
                ('ktopicimgt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvideo1', models.FileField(upload_to='static/images/')),
                ('kvideo2', models.FileField(upload_to='static/images/')),
            ],
        ),
    ]
