# Generated by Django 5.0.3 on 2024-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_kgc1model_kgc2model_kgc3model_kgc4model_kslidermodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bgc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bgc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bgc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bgc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='BsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='BsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='BtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btopicimg', models.ImageField(upload_to='static/images/')),
                ('btopicimgt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvideo1', models.FileField(upload_to='static/images/')),
                ('bvideo2', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cgc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cgc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cgc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cgc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='CsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='CsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='CtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctopicimg', models.ImageField(upload_to='static/images/')),
                ('ctopicimgt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvideo1', models.FileField(upload_to='static/images/')),
                ('cvideo2', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ofgc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofgc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ofgc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofgc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ofgc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofgc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ofgc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofgc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OfsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofsliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OfsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofsvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OftopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oftopicimg', models.ImageField(upload_to='static/images/')),
                ('oftopicimgt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofvideo1', models.FileField(upload_to='static/images/')),
                ('ofvideo2', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ogc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ogc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ogc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ogc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OsliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osliderimg', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Otgc1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otgc1img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Otgc2Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otgc2img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Otgc3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otgc3img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Otgc4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otgc4img', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OtopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otopicimg', models.ImageField(upload_to='static/images/')),
                ('otopicimgt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtsvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsvideo', models.FileField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='OttopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ottopicimg', models.ImageField(upload_to='static/images/')),
                ('ottopicimgt', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OvideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovideo1', models.FileField(upload_to='static/images/')),
                ('kvideo2', models.FileField(upload_to='static/images/')),
            ],
        ),
    ]
