# Generated by Django 5.0.3 on 2024-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimage', models.ImageField(upload_to='static/images/')),
                ('btitle', models.CharField(max_length=100)),
                ('bdate', models.CharField(max_length=12)),
                ('bdis', models.TextField()),
                ('blog_by', models.CharField(max_length=50)),
            ],
        ),
    ]
