# Generated by Django 5.0.3 on 2024-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0016_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
