# Generated by Django 5.0.3 on 2024-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0017_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmphoto', models.ImageField(upload_to='static/images')),
                ('tmname', models.CharField(max_length=100)),
                ('tmposition', models.CharField(max_length=100)),
                ('tmabout', models.CharField(max_length=200)),
                ('tmphone', models.CharField(max_length=15)),
            ],
        ),
    ]
