# Generated by Django 5.0.3 on 2024-04-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0018_membermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovideomodel',
            old_name='kvideo2',
            new_name='ovideo2',
        ),
    ]
