# Generated by Django 5.0.3 on 2024-04-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cmobile', models.CharField(max_length=15)),
                ('cemail', models.EmailField(max_length=254)),
                ('ccity', models.CharField(max_length=20)),
                ('cmessage', models.TextField()),
            ],
        ),
    ]
